<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\tModLoader.targets" />

	<PropertyGroup>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="NLayer">
			<HintPath>lib\NLayer.dll</HintPath>
			<Private>true</Private>
		</Reference>
		<Reference Include="NVorbis">
			<HintPath>C:\Steam\steamapps\common\tModLoader\Libraries\NVorbis\0.10.0.3\NVorbis.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

</Project>
